[package]
name = "sro_macro"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
description = "Serialization traits for Silkroad Online wire types."
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = { workspace = true }
byteorder = { workspace = true }
thiserror = { workspace = true }